{
    "tracks": {
      "href": "https://api.spotify.com/v1/search?query=hello&type=track&offset=0&limit=1",
      "items": [
        {
          "album": {
            "album_type": "album",
            "artists": [
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/4dpARuHxo51G3z768sgnrY"
                },
                "href": "https://api.spotify.com/v1/artists/4dpARuHxo51G3z768sgnrY",
                "id": "4dpARuHxo51G3z768sgnrY",
                "name": "Adele",
                "type": "artist",
                "uri": "spotify:artist:4dpARuHxo51G3z768sgnrY"
              }
            ],
            "available_markets": [
              "AR",
              "BO",
              "BR",
              "CL",
              "CO",
              "CR",
              "DO",
              "EC",
              "GT",
              "HN",
              "MX",
              "NI",
              "PA",
              "PE",
              "PY",
              "SV",
              "US",
              "UY"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/0K4pIOOsfJ9lK8OjrZfXzd"
            },
            "href": "https://api.spotify.com/v1/albums/0K4pIOOsfJ9lK8OjrZfXzd",
            "id": "0K4pIOOsfJ9lK8OjrZfXzd",
            "images": [
              {
                "height": 640,
                "url": "https://i.scdn.co/image/602102500b9cebde7559a5f9c16daaaef2846440",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/1ee2055a078d87a5a55366189409b9e1d820972a",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/7afb855c28a2c8ad5ed9d51460736f4022e60bbf",
                "width": 64
              }
            ],
            "name": "25",
            "release_date": "2016-06-24",
            "release_date_precision": "day",
            "total_tracks": 11,
            "type": "album",
            "uri": "spotify:album:0K4pIOOsfJ9lK8OjrZfXzd"
          },
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/4dpARuHxo51G3z768sgnrY"
              },
              "href": "https://api.spotify.com/v1/artists/4dpARuHxo51G3z768sgnrY",
              "id": "4dpARuHxo51G3z768sgnrY",
              "name": "Adele",
              "type": "artist",
              "uri": "spotify:artist:4dpARuHxo51G3z768sgnrY"
            }
          ],
          "available_markets": [
            "AR",
            "BO",
            "BR",
            "CL",
            "CO",
            "CR",
            "DO",
            "EC",
            "GT",
            "HN",
            "MX",
            "NI",
            "PA",
            "PE",
            "PY",
            "SV",
            "US",
            "UY"
          ],
          "disc_number": 1,
          "duration_ms": 295493,
          "explicit": false,
          "external_ids": {
            "isrc": "GBBKS1500214"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/4sPmO7WMQUAf45kwMOtONw"
          },
          "href": "https://api.spotify.com/v1/tracks/4sPmO7WMQUAf45kwMOtONw",
          "id": "4sPmO7WMQUAf45kwMOtONw",
          "is_local": false,
          "name": "Hello",
          "popularity": 70,
          "preview_url": "https://p.scdn.co/mp3-preview/0b90429fd554bad6785faa2b8931d613db4a0ee4?cid=db33cd70130b4d31a0e471b0de5445c8",
          "track_number": 1,
          "type": "track",
          "uri": "spotify:track:4sPmO7WMQUAf45kwMOtONw"
        }
      ],
      "limit": 1,
      "next": "https://api.spotify.com/v1/search?query=hello&type=track&offset=1&limit=1",
      "offset": 0,
      "previous": null,
      "total": 54544
    }
  }

  //asdfghjkjhgfdsdfghjkjhgfdsdfghjkjhgfds
  //asdfghjkjhgfdsdfghjkjhgfdsdfghjkjhgfds
  //asdfghjkjhgfdsdfghjkjhgfdsdfghjkjhgfds
  //asdfghjkjhgfdsdfghjkjhgfdsdfghjkjhgfds
  //asdfghjkjhgfdsdfghjkjhgfdsdfghjkjhgfds
  //asdfghjkjhgfdsdfghjkjhgfdsdfghjkjhgfds
  //asdfghjkjhgfdsdfghjkjhgfdsdfghjkjhgfds
  { status: 200,
    statusText: 'OK',
    headers:
     { 'content-type': 'application/json',
       'content-length': '10275',
       connection: 'close',
       date: 'Fri, 15 Feb 2019 16:20:43 GMT',
       'x-amzn-requestid': 'a43abe39-313d-11e9-9313-137cfcc6e842',
       'access-control-allow-origin': '*',
       'x-amz-apigw-id': 'VJkCNHrIoAMFwtg=',
       'x-amzn-trace-id': 'Root=1-5c66e6da-fe64a269d3bc264c60c64512;Sampled=0',
       'x-cache': 'Miss from cloudfront',
       via: '1.1 4034587c7184df936ffe61c7ddedcd7d.cloudfront.net (CloudFront)',
       'x-amz-cf-id': 'ifx8018CS2CC4hiC60A4DCIJIocF6b5_6_PLUrxWXdYWI_9p2wVyPQ==' },
    config:
     { adapter: [Function: httpAdapter],
       transformRequest: { '0': [Function: transformRequest] },
       transformResponse: { '0': [Function: transformResponse] },
       timeout: 0,
       xsrfCookieName: 'XSRF-TOKEN',
       xsrfHeaderName: 'X-XSRF-TOKEN',
       maxContentLength: -1,
       validateStatus: [Function: validateStatus],
       headers:
        { Accept: 'application/json, text/plain, */*',
          'User-Agent': 'axios/0.18.0' },
       method: 'get',
       url: 'https://rest.bandsintown.com/artists/bounce/events?app_id=codingbootcamp',
       data: undefined },
    request:
     ClientRequest {
       domain: null,
       _events:
        { socket: [Function],
          abort: [Function],
          aborted: [Function],
          error: [Function],
          timeout: [Function],
          prefinish: [Function: requestOnPrefinish] },
       _eventsCount: 6,
       _maxListeners: undefined,
       output: [],
       outputEncodings: [],
       outputCallbacks: [],
       outputSize: 0,
       writable: true,
       _last: true,
       upgrading: false,
       chunkedEncoding: false,
       shouldKeepAlive: false,
       useChunkedEncodingByDefault: false,
       sendDate: false,
       _removedConnection: false,
       _removedContLen: false,
       _removedTE: false,
       _contentLength: 0,
       _hasBody: true,
       _trailer: '',
       finished: true,
       _headerSent: true,
       socket:
        TLSSocket {
          _tlsOptions: [Object],
          _secureEstablished: true,
          _securePending: false,
          _newSessionPending: false,
          _controlReleased: true,
          _SNICallback: null,
          servername: 'rest.bandsintown.com',
          npnProtocol: false,
          alpnProtocol: false,
          authorized: true,
          authorizationError: null,
          encrypted: true,
          _events: [Object],
          _eventsCount: 9,
          connecting: false,
          _hadError: false,
          _handle: [Object],
          _parent: null,
          _host: 'rest.bandsintown.com',
          _readableState: [Object],
          readable: true,
          domain: null,
          _maxListeners: undefined,
          _writableState: [Object],
          writable: false,
          allowHalfOpen: false,
          _bytesDispatched: 177,
          _sockname: null,
          _pendingData: null,
          _pendingEncoding: '',
          server: undefined,
          _server: null,
          ssl: [Object],
          _requestCert: true,
          _rejectUnauthorized: true,
          parser: null,
          _httpMessage: [Circular],
          [Symbol(asyncId)]: 6,
          [Symbol(bytesRead)]: 0 },
       connection:
        TLSSocket {
          _tlsOptions: [Object],
          _secureEstablished: true,
          _securePending: false,
          _newSessionPending: false,
          _controlReleased: true,
          _SNICallback: null,
          servername: 'rest.bandsintown.com',
          npnProtocol: false,
          alpnProtocol: false,
          authorized: true,
          authorizationError: null,
          encrypted: true,
          _events: [Object],
          _eventsCount: 9,
          connecting: false,
          _hadError: false,
          _handle: [Object],
          _parent: null,
          _host: 'rest.bandsintown.com',
          _readableState: [Object],
          readable: true,
          domain: null,
          _maxListeners: undefined,
          _writableState: [Object],
          writable: false,
          allowHalfOpen: false,
          _bytesDispatched: 177,
          _sockname: null,
          _pendingData: null,
          _pendingEncoding: '',
          server: undefined,
          _server: null,
          ssl: [Object],
          _requestCert: true,
          _rejectUnauthorized: true,
          parser: null,
          _httpMessage: [Circular],
          [Symbol(asyncId)]: 6,
          [Symbol(bytesRead)]: 0 },
       _header: 'GET /artists/bounce/events?app_id=codingbootcamp HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.18.0\r\nHost: rest.bandsintown.com\r\nConnection: close\r\n\r\n',
       _onPendingData: [Function: noopPendingOutput],
       agent:
        Agent {
          domain: null,
          _events: [Object],
          _eventsCount: 1,
          _maxListeners: undefined,
          defaultPort: 443,
          protocol: 'https:',
          options: [Object],
          requests: {},
          sockets: [Object],
          freeSockets: {},
          keepAliveMsecs: 1000,
          keepAlive: false,
          maxSockets: Infinity,
          maxFreeSockets: 256,
          maxCachedSessions: 100,
          _sessionCache: [Object] },
       socketPath: undefined,
       timeout: undefined,
       method: 'GET',
       path: '/artists/bounce/events?app_id=codingbootcamp',
       _ended: true,
       res:
        IncomingMessage {
          _readableState: [Object],
          readable: false,
          domain: null,
          _events: [Object],
          _eventsCount: 3,
          _maxListeners: undefined,
          socket: [Object],
          connection: [Object],
          httpVersionMajor: 1,
          httpVersionMinor: 1,
          httpVersion: '1.1',
          complete: true,
          headers: [Object],
          rawHeaders: [Array],
          trailers: {},
          rawTrailers: [],
          upgrade: false,
          url: '',
          method: null,
          statusCode: 200,
          statusMessage: 'OK',
          client: [Object],
          _consuming: true,
          _dumped: false,
          req: [Circular],
          responseUrl: 'https://rest.bandsintown.com/artists/bounce/events?app_id=codingbootcamp',
          redirects: [],
          read: [Function] },
       aborted: undefined,
       timeoutCb: null,
       upgradeOrConnect: false,
       parser: null,
       maxHeadersCount: null,
       _redirectable:
        Writable {
          _writableState: [Object],
          writable: true,
          domain: null,
          _events: [Object],
          _eventsCount: 2,
          _maxListeners: undefined,
          _options: [Object],
          _ended: true,
          _ending: true,
          _redirectCount: 0,
          _redirects: [],
          _requestBodyLength: 0,
          _requestBodyBuffers: [],
          _onNativeResponse: [Function],
          _currentRequest: [Circular],
          _currentUrl: 'https://rest.bandsintown.com/artists/bounce/events?app_id=codingbootcamp' },
       [Symbol(outHeadersKey)]: { accept: [Array], 'user-agent': [Array], host: [Array]
  } },
    data:
     [ { id: '100753240',
         artist_id: '210047',
         url: 'https://www.bandsintown.com/e/100753240?app_id=codingbootcamp&came_from=267&utm_medium=api&utm_source=public_api&utm_campaign=event',
         on_sale_datetime: '',
         datetime: '2019-02-15T21:30:00',
         description: '',
         venue: [Object],
         lineup: [Array],
         offers: [] },
       { id: '100753245',
         artist_id: '210047',
         url: 'https://www.bandsintown.com/e/100753245?app_id=codingbootcamp&came_from=267&utm_medium=api&utm_source=public_api&utm_campaign=event',
         on_sale_datetime: '',
         datetime: '2019-02-16T21:00:00',
         description: '',
         venue: [Object],
         lineup: [Array],
         offers: [] },
       { id: '100753239',
         artist_id: '210047',
         url: 'https://www.bandsintown.com/e/100753239?app_id=codingbootcamp&came_from=267&utm_medium=api&utm_source=public_api&utm_campaign=event',
         on_sale_datetime: '',
         datetime: '2019-02-22T21:00:00',
         description: '',
         venue: [Object],
         lineup: [Array],
         offers: [] },
       { id: '100753244',
         artist_id: '210047',
         url: 'https://www.bandsintown.com/e/100753244?app_id=codingbootcamp&came_from=267&utm_medium=api&utm_source=public_api&utm_campaign=event',
         on_sale_datetime: '',
         datetime: '2019-02-23T21:00:00',
         description: '',
         venue: [Object],
         lineup: [Array],
         offers: [Array] },
       { id: '100753252',
         artist_id: '210047',
         url: 'https://www.bandsintown.com/e/100753252?app_id=codingbootcamp&came_from=267&utm_medium=api&utm_source=public_api&utm_campaign=event',
         on_sale_datetime: '',
         datetime: '2019-03-01T20:00:00',
         description: '',
         venue: [Object],
         lineup: [Array],
         offers: [] },
       { id: '100753249',
         artist_id: '210047',
         url: 'https://www.bandsintown.com/e/100753249?app_id=codingbootcamp&came_from=267&utm_medium=api&utm_source=public_api&utm_campaign=event',
         on_sale_datetime: '',
         datetime: '2019-03-02T21:00:00',
         description: '',
         venue: [Object],
         lineup: [Array],
         offers: [] },
       { id: '100753258',
         artist_id: '210047',
         url: 'https://www.bandsintown.com/e/100753258?app_id=codingbootcamp&came_from=267&utm_medium=api&utm_source=public_api&utm_campaign=event',
         on_sale_datetime: '',
         datetime: '2019-03-05T21:30:00',
         description: '',
         venue: [Object],
         lineup: [Array],
         offers: [] },
       { id: '100753259',
         artist_id: '210047',
         url: 'https://www.bandsintown.com/e/100753259?app_id=codingbootcamp&came_from=267&utm_medium=api&utm_source=public_api&utm_campaign=event',
         on_sale_datetime: '',
         datetime: '2019-03-08T21:30:00',
         description: '',
         venue: [Object],
         lineup: [Array],
         offers: [] },
       { id: '100753256',
         artist_id: '210047',
         url: 'https://www.bandsintown.com/e/100753256?app_id=codingbootcamp&came_from=267&utm_medium=api&utm_source=public_api&utm_campaign=event',
         on_sale_datetime: '',
         datetime: '2019-03-09T21:30:00',
         description: '',
         venue: [Object],
         lineup: [Array],
         offers: [Array] },
       { id: '100753261',
         artist_id: '210047',
         url: 'https://www.bandsintown.com/e/100753261?app_id=codingbootcamp&came_from=267&utm_medium=api&utm_source=public_api&utm_campaign=event',
         on_sale_datetime: '',
         datetime: '2019-03-15T21:00:00',
         description: '',
         venue: [Object],
         lineup: [Array],
         offers: [] },
       { id: '100753246',
         artist_id: '210047',
         url: 'https://www.bandsintown.com/e/100753246?app_id=codingbootcamp&came_from=267&utm_medium=api&utm_source=public_api&utm_campaign=event',
         on_sale_datetime: '',
         datetime: '2019-03-16T21:00:00',
         description: '',
         venue: [Object],
         lineup: [Array],
         offers: [] },
       { id: '100753251',
         artist_id: '210047',
         url: 'https://www.bandsintown.com/e/100753251?app_id=codingbootcamp&came_from=267&utm_medium=api&utm_source=public_api&utm_campaign=event',
         on_sale_datetime: '',
         datetime: '2019-03-17T21:00:00',
         description: '',
         venue: [Object],
         lineup: [Array],
         offers: [] },
       { id: '100753247',
         artist_id: '210047',
         url: 'https://www.bandsintown.com/e/100753247?app_id=codingbootcamp&came_from=267&utm_medium=api&utm_source=public_api&utm_campaign=event',
         on_sale_datetime: '',
         datetime: '2019-03-22T20:00:00',
         description: '',
         venue: [Object],
         lineup: [Array],
         offers: [] },
       { id: '100753248',
         artist_id: '210047',
         url: 'https://www.bandsintown.com/e/100753248?app_id=codingbootcamp&came_from=267&utm_medium=api&utm_source=public_api&utm_campaign=event',
         on_sale_datetime: '',
         datetime: '2019-03-23T21:30:00',
         description: '',
         venue: [Object],
         lineup: [Array],
         offers: [] },
       { id: '100753250',
         artist_id: '210047',
         url: 'https://www.bandsintown.com/e/100753250?app_id=codingbootcamp&came_from=267&utm_medium=api&utm_source=public_api&utm_campaign=event',
         on_sale_datetime: '',
         datetime: '2019-03-29T21:00:00',
         description: '',
         venue: [Object],
         lineup: [Array],
         offers: [] },
       { id: '100753253',
         artist_id: '210047',
         url: 'https://www.bandsintown.com/e/100753253?app_id=codingbootcamp&came_from=267&utm_medium=api&utm_source=public_api&utm_campaign=event',
         on_sale_datetime: '',
         datetime: '2019-03-30T21:00:00',
         description: '',
         venue: [Object],
         lineup: [Array],
         offers: [] },
       { id: '100753254',
         artist_id: '210047',
         url: 'https://www.bandsintown.com/e/100753254?app_id=codingbootcamp&came_from=267&utm_medium=api&utm_source=public_api&utm_campaign=event',
         on_sale_datetime: '',
         datetime: '2019-04-05T20:00:00',
         description: '',
         venue: [Object],
         lineup: [Array],
         offers: [] },
       { id: '100753263',
         artist_id: '210047',
         url: 'https://www.bandsintown.com/e/100753263?app_id=codingbootcamp&came_from=267&utm_medium=api&utm_source=public_api&utm_campaign=event',
         on_sale_datetime: '',
         datetime: '2019-04-06T21:00:00',
         description: '',
         venue: [Object],
         lineup: [Array],
         offers: [] },
       { id: '100753260',
         artist_id: '210047',
         url: 'https://www.bandsintown.com/e/100753260?app_id=codingbootcamp&came_from=267&utm_medium=api&utm_source=public_api&utm_campaign=event',
         on_sale_datetime: '',
         datetime: '2019-04-12T21:00:00',
         description: '',
         venue: [Object],
         lineup: [Array],
         offers: [Array] },
       { id: '100753255',
         artist_id: '210047',
         url: 'https://www.bandsintown.com/e/100753255?app_id=codingbootcamp&came_from=267&utm_medium=api&utm_source=public_api&utm_campaign=event',
         on_sale_datetime: '',
         datetime: '2019-04-13T19:00:00',
         description: '',
         venue: [Object],
         lineup: [Array],
         offers: [] },
       { id: '100753262',
         artist_id: '210047',
         url: 'https://www.bandsintown.com/e/100753262?app_id=codingbootcamp&came_from=267&utm_medium=api&utm_source=public_api&utm_campaign=event',
         on_sale_datetime: '',
         datetime: '2019-04-19T21:30:00',
         description: '',
         venue: [Object],
         lineup: [Array],
         offers: [] },
       { id: '100753257',
         artist_id: '210047',
         url: 'https://www.bandsintown.com/e/100753257?app_id=codingbootcamp&came_from=267&utm_medium=api&utm_source=public_api&utm_campaign=event',
         on_sale_datetime: '',
         datetime: '2019-04-20T21:30:00',
         description: '',
         venue: [Object],
         lineup: [Array],
         offers: [] } ] }